#!/bin/sh
#
# Set up environment variables for general build tool to operate
#
# Note: requires zlib to be installed into system as pre-req
export ZOPEN_TYPE="TARBALL"
export ZOPEN_TARBALL_URL="https://ftp.gnu.org/gnu/autoconf/autoconf-2.71.tar.gz"
export ZOPEN_TARBALL_DEPS="curl gzip make m4 perl zlib"

export ZOPEN_GIT_URL="https://github.com/autotools-mirror/autoconf.git"
export ZOPEN_GIT_DEPS="git make m4 perl autoconf automake help2man makeinfo xz zlib"

export ZOPEN_EXTRA_CFLAGS=""
export ZOPEN_EXTRA_LDFLAGS=""
export PERL="/bin/env perl"

zopen_append_to_env()
{
cat <<EOF
export autom4te_perllibdir=\${PWD}/share/autoconf
export AC_MACRODIR=\${PWD}/share/autoconf
EOF
}

zopen_check_results()
{
  chk="$2_check.log"

  ac_success=$(grep -c -E '^ *[0-9]+\: .{48}ok$' ${chk})
  ac_failures=$(grep -c -E '^ *[0-9]+\: .{48}FAILED' ${chk})
  ac_expectedFailures=$(grep -c -E '^ *[0-9]+\: .{48}expected failure' ${chk})
  ac_skipped=$(grep -c -E '^ *[0-9]+\: .{48}skipped' ${chk})
  ac_totalTests=$(grep -c -E '^ *[0-9]+\: .{48}' ${chk})

  let t=${ac_success}+${ac_failures}+${ac_expectedFailures}+${ac_skipped}
  if [ ${t} -ne ${ac_totalTests} ] ; then
    echo "Failed to calculate number of test failures."
  fi

  let actualFailures=${ac_failures}+${ac_expectedFailures}
  let totalTests=${ac_totalTests}
  let expectedFailures=12

  cat <<ZZ
actualFailures:$actualFailures
totalTests:$totalTests
expectedFailures:12
ZZ
}

