#!/bin/sh
#
# Set up environment variables for general build tool to operate
#
# Note: requires zlib to be installed into system as pre-req
export ZOPEN_TYPE="TARBALL"
export ZOPEN_TARBALL_URL="https://ftp.gnu.org/gnu/autoconf/autoconf-2.71.tar.gz"
export ZOPEN_TARBALL_DEPS="curl gzip make m4 perl zlib"

export ZOPEN_GIT_URL="https://github.com/autotools-mirror/autoconf.git"
export ZOPEN_GIT_DEPS="git make m4 perl autoconf automake help2man makeinfo xz zlib"

export ZOPEN_EXTRA_CFLAGS=""
export ZOPEN_EXTRA_LDFLAGS=""
export PERL="/bin/env perl"

zopen_append_to_env()
{
cat <<EOF
export autom4te_perllibdir=\${PWD}/share/autoconf
export AC_MACRODIR=\${PWD}/share/autoconf

#To set M4 variable path
if [ -z "${M4_HOME}"  ]; then
    echo "Ensure M4_HOME is set and re-source the .env"
else
    export M4="\$M4_HOME/bin/m4"
fi

EOF
}

zopen_check_results()
{
  return 3 # non-functional
}

